#@ load("@ytt:data", "data")

#@ if/end "tekton-scan-image-template" not in data.values.excluded_blueprints:
---
apiVersion: carto.run/v1alpha1
kind: ClusterImageTemplate
metadata:
  name: tekton-scan-image-template
  annotations:
    doc: |
      Consumes an application container image and executes a Tekton scanning task
      on every detected input change, using the configured vulnerability scanner.
spec:
  params:
    - name: scannerName
      default: trivy
    - name: pipelineCatalogNamespace
      default: #@ data.values.tekton_catalog_namespace
    - name: serviceAccount
      default: default
  
  imagePath: .spec.params[0].value
  
  lifecycle: tekton
  
  ytt: |
    #@ load("@ytt:assert", "assert")
    #@ load("@ytt:data", "data")

    #@ def param(key):
    #@   if not key in data.values.params:
    #@     return None
    #@   end
    #@   return data.values.params[key]
    #@ end

    #@ def merge_labels(fixed_values):
    #@   labels = {}
    #@   if hasattr(data.values.workload.metadata, "labels"):
    #@     labels.update(data.values.workload.metadata.labels)
    #@   end
    #@   labels.update(fixed_values)
    #@   return labels
    #@ end

    #@ vulnerabilityScanner = param("scannerName")
    #@ validVulnerabilityScanners = ["grype", "trivy"]
    #@ if vulnerabilityScanner not in validVulnerabilityScanners:
    #@   assert.fail("{} not in {}".format(vulnerabilityScanner, validVulnerabilityScanners))
    #@ end

    ---
    apiVersion: tekton.dev/v1
    kind: TaskRun
    metadata:
      generateName: #@ data.values.workload.metadata.name + "-image-scan-"
      labels: #@ merge_labels({ "app.kubernetes.io/component": "image-scan" })
    spec:
      serviceAccountName: #@ data.values.params.serviceAccount
      taskRef:
        resolver: cluster
        params:
        - name: kind
          value: task
        - name: name
          value: #@ vulnerabilityScanner + "-scan-image"
        - name: namespace
          value: #@ data.values.params.pipelineCatalogNamespace
      params:
      - name: image
        value: #@ data.values.image
