#@ load("@ytt:data", "data")
#@ load("/helpers.star", "config_writer")

#@ if/end data.values.supply_chain == "advanced" and "source-to-url-advanced" not in data.values.excluded_blueprints:
---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: source-to-url-advanced
spec:
  selector:
    app.kadras.io/workload-type: web
  
  serviceAccountRef:
    name: #@ data.values.service_account

  resources:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: flux-source-template
      params:
        - name: gitCredentialsSecret
          default: #@ data.values.git_credentials_secret
        - name: serviceAccount
          default: #@ data.values.service_account
    
    - name: source-tester
      templateRef:
        kind: ClusterSourceTemplate
        options:
          - name: tekton-test-source-template
            selector:
              matchExpressions:
                - { key: app.kadras.io/has-tests, operator: Exists }
          - passThrough: source
            selector:
              matchExpressions:
                - { key: app.kadras.io/has-tests, operator: DoesNotExist }
      params:
        - name: serviceAccount
          default: #@ data.values.service_account
      sources:
        - resource: source-provider
          name: source
    
    - name: source-scanner
      templateRef:
        kind: ClusterSourceTemplate
        name: tekton-scan-source-template
      params:
        - name: serviceAccount
          default: #@ data.values.service_account
      sources:
        - resource: source-tester
          name: source

    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: kpack-template
      params:
        - name: clusterBuilder
          default: #@ data.values.cluster_builder
        - name: registry
          value: #@ data.values.registry
        - name: serviceAccount
          default: #@ data.values.service_account
      sources:
        - resource: source-scanner
          name: source
    
    - name: image-scanner
      templateRef:
        kind: ClusterImageTemplate
        name: tekton-scan-image-template
      params:
        - name: serviceAccount
          default: #@ data.values.service_account
      images:
        - resource: image-builder
          name: image
    
    - name: convention-provider
      templateRef:
        kind: ClusterConfigTemplate
        name: convention-template
      params:
        - name: serviceAccount
          default: #@ data.values.service_account
      images:
      - resource: image-scanner
        name: image
    
    - name: config-provider
      templateRef:
        kind: ClusterConfigTemplate
        name: knative-config-template
      configs:
        - resource: convention-provider
          name: config
    
    - name: config-writer
      templateRef:
        kind: ClusterTemplate
        name: #@ config_writer()
      params:
        - name: ca_cert_data
          value: #@ data.values.ca_cert_data
        - name: gitops
          default: #@ data.values.gitops
        - name: registry
          value: #@ data.values.registry
        - name: serviceAccount
          default: #@ data.values.service_account
      configs:
        - resource: config-provider
          name: config   

    - name: deliverable-provider
      templateRef:
        kind: ClusterConfigTemplate
        options:
          - name: deliverable-carvel-app-template
            selector:
              matchLabels:
                app.kadras.io/deliverable-type: carvel-app
          - name: deliverable-flux-kustomization-template
            selector:
              matchLabels:
                app.kadras.io/deliverable-type: flux-kustomization
      params:
        - name: gitCredentialsSecret
          default: #@ data.values.git_credentials_secret
        - name: gitops
          default: #@ data.values.gitops
        - name: registry
          value: #@ data.values.registry
        - name: registryCredentialsSecret
          default: canonical-registry-credentials
        - name: serviceAccount
          default: #@ data.values.service_account
    
    #@ if/end not data.values.external_delivery:
    - name: app-deployer
      templateRef:
        kind: ClusterTemplate
        name: app-gitops-deployment-template
      params:
        - name: serviceAccount
          default: #@ data.values.service_account
      configs:
        - resource: deliverable-provider
          name: config
