#@ load("@ytt:data", "data")
#@ load("/helpers.star", "config_writer")

#@ if/end data.values.supply_chain == "basic" and "source-to-url-basic" not in data.values.excluded_blueprints:
---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: source-to-url-basic
spec:
  selector:
    app.kadras.io/workload-type: web
  
  serviceAccountRef:
    name: #@ data.values.service_account

  resources:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: flux-source-template
      params:
        - name: gitCredentialsSecret
          default: #@ data.values.git_credentials_secret
        - name: serviceAccount
          default: #@ data.values.service_account

    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: kpack-template
      params:
        - name: clusterBuilder
          default: #@ data.values.cluster_builder
        - name: registry
          value: #@ data.values.registry
        - name: serviceAccount
          default: #@ data.values.service_account
      sources:
        - resource: source-provider
          name: source
    
    - name: convention-provider
      templateRef:
        kind: ClusterConfigTemplate
        name: convention-template
      params:
        - name: serviceAccount
          default: #@ data.values.service_account
      images:
      - resource: image-builder
        name: image
    
    - name: config-provider
      templateRef:
        kind: ClusterConfigTemplate
        name: knative-config-template
      configs:
        - resource: convention-provider
          name: config
    
    - name: app-deployer
      templateRef:
        kind: ClusterTemplate
        name: app-local-deployment-template
      params:
        - name: serviceAccount
          default: #@ data.values.service_account
      configs:
        - resource: config-provider
          name: config
