#@ load("@ytt:data", "data")
#@ load("/helpers.star", "config_writer")

#@ if/end data.values.supply_chain == "advanced":
---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: supply-chain-advanced
spec:
  selector:
    apps.kadras.io/workload-type: web

  params:
    - name: gitops_user_name
      default: #@ data.values.gitops.user_name
    - name: gitops_user_email
      default: #@ data.values.gitops.user_email

    - name: gitops_commit_message
      default: #@ data.values.gitops.commit_message
    - name: gitops_branch
      default: #@ data.values.gitops.branch
    
    #@ if/end data.values.gitops.server_address:
    - name: gitops_server_address
      default: #@ data.values.gitops.server_address
    #@ if/end data.values.gitops.repository_owner:
    - name: gitops_repository_owner
      default: #@ data.values.gitops.repository_owner
    #@ if/end data.values.gitops.repository_name:
    - name: gitops_repository_name
      default: #@ data.values.gitops.repository_name

    #@ if data.values.gitops.commit_strategy == "pull_request":
    #@ if/end data.values.gitops.pull_request.server_kind:
    - name: gitops_server_kind
      default: #@ data.values.gitops.pull_request.server_kind
    #@ if/end "commit_branch" in data.values.gitops.pull_request:
    - name: gitops_commit_branch
      default: #@ data.values.gitops.pull_request.commit_branch
    #@ if/end data.values.gitops.pull_request.pull_request_title:
    - name: gitops_pull_request_title
      default: #@ data.values.gitops.pull_request.pull_request_title
    #@ if/end data.values.gitops.pull_request.pull_request_body:
    - name: gitops_pull_request_body
      default: #@ data.values.gitops.pull_request.pull_request_body
    #@ end

  resources:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: supplychain-source-template
      params:
        - name: serviceAccount
          value: #@ data.values.service_account
        - name: gitImplementation
          value: #@ data.values.git_implementation
        - name: gitops_access_secret
          default: #@ data.values.gitops.access_secret
    
    - name: source-tester
      templateRef:
        kind: ClusterSourceTemplate
        options:
          - name: tekton-test-source-template
            selector:
              matchExpressions:
                - { key: apps.kadras.io/has-tests, operator: Exists }
          - passThrough: source
            selector:
              matchExpressions:
                - { key: apps.kadras.io/has-tests, operator: DoesNotExist }
      sources:
        - resource: source-provider
          name: source
    
    - name: source-scanner
      templateRef:
        kind: ClusterSourceTemplate
        name: tekton-scan-source-template
      sources:
        - resource: source-tester
          name: source

    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: kpack-template
      params:
        - name: serviceAccount
          value: #@ data.values.service_account
        - name: registry
          value: #@ data.values.registry
        - name: clusterBuilder
          default: #@ data.values.cluster_builder
      sources:
        - resource: source-scanner
          name: source
    
    - name: image-scanner
      templateRef:
        kind: ClusterImageTemplate
        name: tekton-scan-image-template
      params:
        - name: serviceAccount
          value: #@ data.values.service_account
      images:
        - resource: image-builder
          name: image
    
    - name: convention-provider
      templateRef:
        kind: ClusterConfigTemplate
        name: convention-template
      params:
        - name: serviceAccount
          value: #@ data.values.service_account
      images:
      - resource: image-scanner
        name: image
    
    - name: config-provider
      templateRef:
        kind: ClusterConfigTemplate
        name: knative-config-template
      configs:
        - resource: convention-provider
          name: config
    
    - name: config-writer
      templateRef:
        kind: ClusterTemplate
        name: #@ config_writer()
      params:
        - name: serviceAccount
          value: #@ data.values.service_account
        - name: registry
          value: #@ data.values.registry
      configs:
        - resource: config-provider
          name: config     
    
    - name: deliverable
      templateRef:
        kind: ClusterTemplate
        name: deliverable-template
      params:
        - name: registry
          value: #@ data.values.registry
        - name: gitops_access_secret
          default: #@ data.values.gitops.access_secret
