#@ load("@ytt:data", "data")

#@ if/end "flux-source-template" not in data.values.excluded_blueprints:
---
apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: flux-source-template
  annotations:
    doc: |
      Using Flux Source Controller, this template consumes an application Git repository via a Git server
      or OCI registry, and passes it down to the rest of the supply chain on every code change.
spec:
  params:
    - name: gitCredentialsSecret
      default: ""
    - name: serviceAccount
      default: default

  urlPath: .status.artifact.url
  revisionPath: .status.artifact.revision

  healthRule:
    singleConditionType: Ready

  ytt: |
    #@ load("@ytt:data", "data")

    #@ def param(key):
    #@   if not key in data.values.params:
    #@     return None
    #@   end
    #@   return data.values.params[key]
    #@ end

    #@ def merge_labels(fixed_values):
    #@   labels = {}
    #@   if hasattr(data.values.workload.metadata, "labels"):
    #@     labels.update(data.values.workload.metadata.labels)
    #@   end
    #@   labels.update(fixed_values)
    #@   return labels
    #@ end

    #@ if/end hasattr(data.values.workload.spec.source, "git"):
    ---
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    metadata:
      name: #@ data.values.workload.metadata.name
      labels: #@ merge_labels({ "app.kubernetes.io/component": "source" })
    spec:
      interval: 1m0s
      url: #@ data.values.workload.spec.source.git.url
      ref: #@ data.values.workload.spec.source.git.ref
      #@ if/end param("gitCredentialsSecret"):
      secretRef:
        name: #@ param("gitCredentialsSecret")
    
    #@ if hasattr(data.values.workload.spec.source, "image"):
    #@   oci_artifact = data.values.workload.spec.source.image.split(":latest@", 1)
    #@ end

    #@ if/end hasattr(data.values.workload.spec.source, "image"):
    ---
    apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: OCIRepository
    metadata:
      name: #@ data.values.workload.metadata.name
      labels: #@ merge_labels({ "app.kubernetes.io/component": "source" })
    spec:
      serviceAccountName: #@ data.values.params.serviceAccount
      interval: 1m0s
      url: #@ "oci://" + oci_artifact[0]
      ref:
        digest: #@ oci_artifact[1]
